version: '3'
services:

  shiny:
    container_name: shiny_cbass
    build: .
    ports:
      - "3838:3838"
    environment:
      - R_LIBS_USER=/opt/conda/lib/R/library
    restart: unless-stopped
    volumes:
      - local-path-to-swag-config:/config
      - local-path-to-uploaded-data:/home/data/Uploaded_xlsx
    networks:
      - swag_net

networks:
  swag_net:
    external: true

